export type jobsTypes = {
  title: string
  description: string
  company: string
  location: string
  date: string
  logo: string
  new: boolean
}

export const jobsData: jobsTypes[] = [
  {
    title: 'Software Engineer',
    description: 'Develop and maintain web applications.',
    company: 'TechCorp',
    location: 'New York, NY',
    date: '2024-05-01',
    logo: 'https://example.com/logos/techcorp.png',

    new: true,
  },
  {
    title: 'Product Manager',
    description: 'Lead product development teams.',
    company: 'Innovatech',
    location: 'San Francisco, CA',
    date: '2024-04-25',
    logo: 'https://example.com/logos/innovatech.png',
    new: false,
  },
  {
    title: 'Data Scientist',
    description: 'Analyze data to provide business insights.',
    company: 'DataMinds',
    location: 'Austin, TX',
    date: '2024-05-10',
    logo: 'https://example.com/logos/dataminds.png',
    new: true,
  },
  {
    title: 'UX Designer',
    description: 'Design user-friendly interfaces.',
    company: 'DesignHub',
    location: 'Los Angeles, CA',
    date: '2024-05-05',
    logo: 'https://example.com/logos/designhub.png',
    new: true,
  },
  {
    title: 'Marketing Specialist',
    description: 'Develop and implement marketing strategies.',
    company: 'MarketGurus',
    location: 'Chicago, IL',
    date: '2024-05-12',
    logo: 'https://example.com/logos/marketgurus.png',
    new: false,
  },
  {
    title: 'DevOps Engineer',
    description: 'Maintain and improve CI/CD pipelines.',
    company: 'CloudWorks',
    location: 'Seattle, WA',
    date: '2024-05-07',
    logo: 'https://example.com/logos/cloudworks.png',
    new: true,
  },
  {
    title: 'HR Manager',
    description: 'Manage human resources activities.',
    company: 'PeopleFirst',
    location: 'Atlanta, GA',
    date: '2024-04-30',
    logo: 'https://example.com/logos/peoplefirst.png',
    new: false,
  },
  {
    title: 'Financial Analyst',
    description: 'Analyze financial data and trends.',
    company: 'FinancePros',
    location: 'Boston, MA',
    date: '2024-05-09',
    logo: 'https://example.com/logos/financepros.png',
    new: true,
  },
  {
    title: 'Project Manager',
    description: 'Oversee project timelines and deliverables.',
    company: 'ProjectFlow',
    location: 'Denver, CO',
    date: '2024-05-03',
    logo: 'https://example.com/logos/projectflow.png',
    new: true,
  },
  {
    title: 'Sales Executive',
    description: 'Drive sales and meet targets.',
    company: 'SalesForceX',
    location: 'Dallas, TX',
    date: '2024-05-11',
    logo: 'https://example.com/logos/salesforcex.png',
    new: false,
  },
  {
    title: 'Customer Support Specialist',
    description: 'Assist customers with their queries.',
    company: 'HelpDesk Solutions',
    location: 'Miami, FL',
    date: '2024-05-06',
    logo: 'https://example.com/logos/helpdesksolutions.png',
    new: true,
  },
  {
    title: 'Content Writer',
    description: 'Create engaging content for various platforms.',
    company: 'WriteWell',
    location: 'San Diego, CA',
    date: '2024-05-08',
    logo: 'https://example.com/logos/writewell.png',
    new: true,
  },
  {
    title: 'Network Administrator',
    description: 'Manage and maintain network infrastructure.',
    company: 'NetSecure',
    location: 'Phoenix, AZ',
    date: '2024-05-04',
    logo: 'https://example.com/logos/netsecure.png',
    new: false,
  },
  {
    title: 'Graphic Designer',
    description: 'Create visual content for marketing campaigns.',
    company: 'CreativeArts',
    location: 'Portland, OR',
    date: '2024-04-28',
    logo: 'https://example.com/logos/creativearts.png',
    new: true,
  },
  {
    title: 'IT Support Specialist',
    description: 'Provide technical support to employees.',
    company: 'TechSupport Inc.',
    location: 'San Jose, CA',
    date: '2024-05-02',
    logo: 'https://example.com/logos/techsupportinc.png',
    new: false,
  },
  {
    title: 'Operations Manager',
    description: 'Oversee daily operations of the company.',
    company: 'BizOps',
    location: 'Las Vegas, NV',
    date: '2024-05-01',
    logo: 'https://example.com/logos/bizops.png',
    new: true,
  },
  {
    title: 'Business Analyst',
    description: 'Analyze business processes and recommend improvements.',
    company: 'BizInsights',
    location: 'Salt Lake City, UT',
    date: '2024-05-03',
    logo: 'https://example.com/logos/bizinsights.png',
    new: true,
  },
  {
    title: 'Software Tester',
    description: 'Test software applications for bugs and issues.',
    company: 'QualityCheck',
    location: 'Raleigh, NC',
    date: '2024-05-06',
    logo: 'https://example.com/logos/qualitycheck.png',
    new: false,
  },
  {
    title: 'SEO Specialist',
    description: 'Optimize websites for search engines.',
    company: 'SearchOptimize',
    location: 'Orlando, FL',
    date: '2024-04-29',
    logo: 'https://example.com/logos/searchoptimize.png',
    new: true,
  },
  {
    title: 'Recruiter',
    description: 'Find and hire the best talent.',
    company: 'TalentFind',
    location: 'Charlotte, NC',
    date: '2024-05-07',
    logo: 'https://example.com/logos/talentfind.png',
    new: false,
  },
]
